### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by seife** [mchlbrnhrd/mbLib#1]
Hi,

I wanted to use mbLib in an own project. However, it's license is unclear.

All that is written is "All rights reserved" in every source file, which means nobody is entitled to use it for anything, right?

**Comment by mchlbrnhrd** [comment]
Hi,
thanks for the hint. I removed the "all rights reserved" from the files. So you can use the files in your own project.

**Comment by mchlbrnhrd** [comment]
added "GNU General Public License v3.0"
