### ISSUE TITLE
What would I have to do do to modify it for a 4x20 character display?

### ISSUE THREAD

**Issue by StefanL38** [mchlbrnhrd/mbLib#2]
Hi Bernhard,

It took me quite some time to understand the details how your library is working in principle.
I haven't looked yet in the source-code of the library-files

What would I have to do do to modify it for a 4x20 character display?
or is it just usable with 2x16 displays?

best regards Stefan

**Comment by mchlbrnhrd** [comment]
Hi Stefan,
the _mbLib_ is independent of the LCD module. So you can use whatever you want.
Have a look at the example: [menuExampleLCD.ino](https://github.com/mchlbrnhrd/mbLib/blob/main/examples/menuExampleLCD/menuExampleLCD.ino)
Replace _g_Lcd_ with your LCD module. I.e. call the required init routines etc.
In the function _printMenuEntry_ of this example you will find _print on LCD_ (line 216 of the current commit). There you can control how and in which line the menu info should be printed out.

Remark: In [CMBMenu.hpp](https://github.com/mchlbrnhrd/mbLib/blob/main/src/CMBMenu.hpp) there is a function _printMenu_. This is used for debugging: via serial port the whole menu is printed out. If you want, you can extend the code to print out the whole menu on LCD for example.

Kind Regards
